### ISSUE TITLE
주차별 스프린트의 중요성...

### ISSUE THREAD

**Issue by lettuce82** [nhnacademy-be6-yes-25-5/scrum#116]
주차별 팀 목표가 생기니 프로젝트의 방향성과 윤곽이 보이는 것 같아 작업하기가 훨씬 수월했습니다. 이번 주에도 팀 목표대로 작업해 보면 좋을 것 같습니다!

**Comment by Limchaereong** [comment]
맞아요 화이팅 !!!!

**Comment by wnstj1548** [comment]
저두 목표생기니까 좀 더 편했던 거 같아요!
