### ISSUE TITLE
아픈 손가락 코드 리뷰...

### ISSUE THREAD

**Issue by lettuce82** [nhnacademy-be6-yes-25-5/scrum#133]
당장 저부터도 맡은 부분 구현에 급급해서 흐린 눈으로 pr 알람 보고 있기는 하지만...
이번 주부터는 다시 열심히 코드 리뷰 작성하도록 하겠습니다!
# 다짐!

**Comment by wnstj1548** [comment]
계속 코딩하다보면 잊어버리는 경우가 있는거같아요 ㅠ
