### ISSUE TITLE
배포 후 서버가 잘 살아있는지 확인했으면 좋겠습니다

### ISSUE THREAD

**Issue by bbbbooo** [nhnacademy-be6-yes-25-5/scrum#85]
[Description]

- 주말에 저 포함 도커 둘러보는데 환경변수 설정 안된게 그대로 올라가있거나 아예 죽었는데 확인이 안됐다거나... 
- 진척도 보니까 배포 기준으로 평가하더루가여. 저희 한건 많은데 배포가 잘 안되어있어서 보여준게 많이 없네여

**Comment by lettuce82** [comment]
저도 주말에 cd 고치고 난리도 아니었습니다.... 올릴 때마다 각자 확인해 봐야겠어요!

**Comment by Limchaereong** [comment]
이번주는 화이팅해서 배포 많이해요 !!!!!!!!!!!!!!

**Comment by wnstj1548** [comment]
ci/cd 중요성을 다시 깨달았습니다. 다음 진척도때는 많이 보여줍시당

**Comment by Limchaereong** [comment]
배포후에 할때마다 서버 한번씩 다 돌려서 확인해보고 서버 확인까지 두레이 남기기 어때요
